org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Avoid Kotlin daemon cache file creation errors (e.g. source-to-classes.tab)
kotlin.compiler.execution.strategy=in-process
# Use AGP 9's built-in Kotlin support.
android.builtInKotlin=true
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
